### ISSUE TITLE
F28 RPM with QT4/Javascript MIDI problems.

### ISSUE THREAD

**Issue by wgold** [UnitedRPMs/mixxx#1]
The Javascript interpreter in qt4 in F28 seems to have problems. Therefore the JS bindings of the controller functions don't work anymore in mixxx. Compiling it with qt5=1 seems to be a workaround.
https://bugs.launchpad.net/mixxx/+bug/1770079

**Comment by kuboosoft** [comment]
@wgold Thanks; We are working now it to solve the issue.

**Comment by kuboosoft** [comment]
@wgold Thanks; Very strange; our mixxx uses qt5...
https://github.com/UnitedRPMs/mixxx/blob/master/mixxx.spec#L39
https://github.com/UnitedRPMs/mixxx/blob/master/mixxx.spec#L217

**Comment by sergiomb2** [comment]
%bcond_with _qt5 means you may add --with _qt5 to work so if fedora  >= 30 it will disable qt5 ! , and well qt5 is enable (with a big confusion of if :smile: ) 
in RPMFusion qt4 is enabled .

I think you want something like this : 

```
%if 0%{?fedora} && 0%{?fedora} < 25
%bcond_with _qt5
%else
%bcond_without _qt5
%endif


```

**Comment by Be-ing** [comment]
Do not distribute Mixxx 2.1.x with Qt5. It has only received minimal testing. A fix for Fedora's qt (Qt4) package is already in updates-testing.

**Comment by kuboosoft** [comment]
@sergiomb2 naaa 
https://github.com/UnitedRPMs/mixxx/blob/master/mixxx.spec#L38

@Be-ing But we need work around it... and with qt5 works fine...

**Comment by kuboosoft** [comment]
@sergiomb2 naaa; the same but inverse...If we think the same; the world would be chaos. :) 
https://github.com/UnitedRPMs/mixxx/blob/master/mixxx.spec#L38

@Be-ing But we need work around it... and with qt5 works fine...

**Comment by kuboosoft** [comment]
@sergiomb2 naaa; the same but inverse...If we think the same; the world would be chaos. :smile_cat: 
https://github.com/UnitedRPMs/mixxx/blob/master/mixxx.spec#L38
Also, our mixxx is from scratch :star2: 

@Be-ing But we need work around it... and with qt5 works fine... We are testing it in F26-F29 :smile_cat:

**Comment by Be-ing** [comment]
:man_shrugging: Ignore packaging recommendations from upstream at your own risk.

**Comment by kuboosoft** [comment]
@Be-ing we can help you to test mixxx with qt5; I am not sure if exist other project using qt5 with mixxx; only a patch was necessary, because Fedora es Multilib. Kdenlive and other packages uses qt5; why not make the complete change? In Fedora we have a acelated rithm. We can merge forces.

The world is of risks; and mixxx is a wonderful project; if a good people do not report the issue with qt4; Then mixxx; It was working for a limited group; the people using a build with qt5; the users of UnitedRPMs .

**Comment by Be-ing** [comment]
Mixxx is an application designed for live performance. As such, shipping untested modifications could mean a crash that interrupts a performance. Qt4 to Qt5 is a big change and it's impossible to anticipate all the consequences. Indeed, I have been testing Mixxx with Qt5 myself to work around this issue since updating to Fedora 28 and have twice run into a bug that made the GUI completely unresponsive that never happened with Qt4. We will finally be upgrading to Qt5 for the next Mixxx release.

**Comment by kuboosoft** [comment]
@Be-ing check our [.spec](https://github.com/UnitedRPMs/mixxx/blob/master/mixxx.spec); inclusive we are using clang for build; and an specific scons; we have various months testing mixxx.  The next release will surely be great. Mixxx is an important piece to every musician in the Linux world and others.

**Comment by Be-ing** [comment]
Why are you building with Clang? We use Clang to build for macOS, but Mixxx built with Clang is not extensively tested on Linux. I recommend using GCC unless you have a good reason not to.

**Comment by kuboosoft** [comment]
@Be-ing for a super fast build; mixxx takes 10-12 minutes (theoretically, clang is compatible with gcc), beatiful!... Testing I have problems now; building in F28 (with the current clang 6.0.0 ); current commit.

**Comment by Be-ing** [comment]
The fixed qt package is [now in Fedora updates](https://bugzilla.redhat.com/show_bug.cgi?id=1580047), so this issue is solved.

> theoretically, clang is compatible with gcc

Theoretically, but compiler bugs happen, hence this issue existing in the first place.

**Comment by kuboosoft** [comment]
@Be-ing I am testing now; our automatic test tool failed build mixxx; but we are waiting for our 'mock' build...

**Comment by kuboosoft** [comment]
@Be-ing I am testing now; our automatic test tool failed build mixxx (gcc and clang); but we are waiting for our 'mock' build...
